services:
  - type: web
    name: car-auction-api
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn config.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: car_auction_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "car-auction-backend.onrender.com,.onrender.com"
      - key: FRONTEND_URL
        value: "https://car-auction-ww5s.onrender.com"
      - key: DJANGO_SETTINGS_MODULE
        value: "config.settings_prod"

databases:
  - name: car_auction_db
    databaseName: car_auction
    user: car_auction
